[package]
name = "librypt-hash-sha3"
version = "0.1.0"
edition = "2021"

[dependencies]
librypt-hash = { version = "0.1", git = "https://www.github.com/librypt/librypt-hash" }

[dev-dependencies]
hex = "0.4"
